[include]
# paths = ["/etc/topgrade.toml"]

[misc]

only = ["brew_cask", "brew_formula", "bun", "bun_packages", "cargo", "chezmoi", "custom_commands", "deno", "distrobox", "dotnet", "gearlever", "getnf", "github_cli_extensions", "go", "helix", "ollama", "pip3", "pipx", "poetry", "pnpm", "protonplus", "rustup", "shell", "tldr", "toolbx", "uv", "vscode", "vscodium"]

[commands]
"skills" = "bunx skills update --global"
